<?php

namespace Tests;

class TestData
{

	/*
	 * EPI testdata
	 */
	public static function getRecipients($mailingTrigger)
	{
		return [
			'recipients' => [
				[
					'data' => [
						'salutation' => 'FRAU',
						'title' => 'Dr.',
						'firstname' => 'Chiara',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-001',
						'sc_id' => '558',
						'sc_name' => 'Euromaster Bad Camberg',
						'sc_address' => 'Limburger Str. 51-53',
						'sc_zip' => '65520',
						'sc_city' => 'Bad Camberg',
						'sc_phone' => '0 64 34 - 50 11',
						'last_visit' => '2019-07-24T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '1',
						'mailing_product' => '1'
					],
					'id' => 'chiara.riley@2hm-bs.com',
				],
				[
					'data' => [
						'salutation' => 'HERR',
						'title' => '',
						'firstname' => 'Chiara',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-002',
						'sc_id' => '504',
						'sc_name' => 'Euromaster Grünstadt/Pfalz',
						'sc_address' => 'Industriestr. 16',
						'sc_zip' => '67269',
						'sc_city' => 'Grünstadt/Pfalz',
						'sc_phone' => '0 63 59 - 8 30 22',
						'last_visit' => '2019-07-23T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '1',
						'mailing_product' => '2'
					],
					'id' => 'riley@2hm-bs.com',
				],
				[
					'data' => [
						'salutation' => 'FIRMA',
						'title' => '',
						'firstname' => 'Antonia',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-003',
						'sc_id' => '250',
						'sc_name' => 'Euromaster Berlin-Hohenschoenhausen',
						'sc_address' => 'Gehrenseestr. 43',
						'sc_zip' => '13053',
						'sc_city' => 'Berlin-Hohenschoenhausen',
						'sc_phone' => '0 30 - 93 52 36 00',
						'last_visit' => '2019-07-25T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '1',
						'mailing_product' => '3'
					],
					'id' => 'hoebbel@2hm-bs.com',
				],
				[
					'data' => [
						'salutation' => '',
						'title' => 'Prof.',
						'firstname' => 'Antonia',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-004',
						'sc_id' => '252',
						'sc_name' => 'Euromaster Berlin-Bohnstorf bei Schoenefeld',
						'sc_address' => 'Grünbergallee 274',
						'sc_zip' => '12526',
						'sc_city' => 'Berlin-Bohnstorf bei Schoenefeld',
						'sc_phone' => '0 30 - 67 68 90 33',
						'last_visit' => '2019-06-20T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '1',
						'mailing_product' => '4'
					],
					'id' => 'antonia.hoebbel@2hm-bs.com',
				],
				[
					'data' => [
						'salutation' => 'FRAU',
						'title' => '',
						'firstname' => 'Mia',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-005',
						'sc_id' => '327',
						'sc_name' => 'Euromaster Mönchengladbach-Rheydt',
						'sc_address' => 'Giesenkirchener Str. 17',
						'sc_zip' => '41238',
						'sc_city' => 'Mönchengladbach-Rheydt',
						'sc_phone' => '0 21 66 - 18 70 51',
						'last_visit' => '2019-07-24T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '1',
						'mailing_product' => '5'
					],
					'id' => 'maria.cezanne@2hm-bs.com',
				],
				[
					'data' => [
						'salutation' => 'HERR',
						'title' => '',
						'firstname' => 'Flo',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-006',
						'sc_id' => '558',
						'sc_name' => 'Euromaster Bad Camberg',
						'sc_address' => 'Limburger Str. 51-53',
						'sc_zip' => '65520',
						'sc_city' => 'Bad Camberg',
						'sc_phone' => '0 64 34 - 50 11',
						'last_visit' => '2019-07-24T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '1',
						'mailing_product' => '6'
					],
					'id' => 'florian.caspar@2hm-bs.com',
				],
				[
					'data' => [
						'salutation' => 'FIRMA',
						'title' => '',
						'firstname' => 'Mia',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-007',
						'sc_id' => '504',
						'sc_name' => 'Euromaster Grünstadt/Pfalz',
						'sc_address' => 'Industriestr. 16',
						'sc_zip' => '67269',
						'sc_city' => 'Grünstadt/Pfalz',
						'sc_phone' => '0 63 59 - 8 30 22',
						'last_visit' => '2019-07-24T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '1',
						'mailing_product' => '7'
					],
					'id' => 'maria.ugur@2hm-bs.com',
				],
				[
					'data' => [
						'salutation' => '',
						'title' => '',
						'firstname' => 'Mia',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-008',
						'sc_id' => '250',
						'sc_name' => 'Euromaster Berlin-Hohenschoenhausen',
						'sc_address' => 'Gehrenseestr. 43',
						'sc_zip' => '13053',
						'sc_city' => 'Berlin-Hohenschoenhausen',
						'sc_phone' => '0 30 - 93 52 36 00',
						'last_visit' => '2019-07-24T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '1',
						'mailing_product' => '8'
					],
					'id' => 'ugur@2hm-bs.com',
				],
				[
					'data' => [
						'salutation' => '',
						'title' => '',
						'firstname' => '',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-009',
						'sc_id' => '252',
						'sc_name' => 'Euromaster Berlin-Bohnstorf bei Schoenefeld',
						'sc_address' => 'Grünbergallee 274',
						'sc_zip' => '12526',
						'sc_city' => 'Berlin-Bohnstorf bei Schoenefeld',
						'sc_phone' => '0 30 - 67 68 90 33',
						'last_visit' => '2019-07-24T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '2',
						'mailing_product' => '9'
					],
					'id' => 'nlbs2015@gmx.de',
				],
				[
					'data' => [
						'salutation' => '',
						'title' => '',
						'firstname' => '',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-010',
						'sc_id' => '327',
						'sc_name' => 'Euromaster Mönchengladbach-Rheydt',
						'sc_address' => 'Giesenkirchener Str. 17',
						'sc_zip' => '41238',
						'sc_city' => 'Mönchengladbach-Rheydt',
						'sc_phone' => '0 21 66 - 18 70 51',
						'last_visit' => '2019-07-24T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '2',
						'mailing_product' => '10'
					],
					'id' => 'nlbs2015@t-online.de',
				],
				[
					'data' => [
						'salutation' => '',
						'title' => '',
						'firstname' => '',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-011',
						'sc_id' => '558',
						'sc_name' => 'Euromaster Bad Camberg',
						'sc_address' => 'Limburger Str. 51-53',
						'sc_zip' => '65520',
						'sc_city' => 'Bad Camberg',
						'sc_phone' => '0 64 34 - 50 11',
						'last_visit' => '2019-07-24T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '2',
						'mailing_product' => '11'
					],
					'id' => 'nlbs2015@web.de',
				],
				[
					'data' => [
						'salutation' => 'FRAU',
						'title' => '',
						'firstname' => '',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-012',
						'sc_id' => '504',
						'sc_name' => 'Euromaster Grünstadt/Pfalz',
						'sc_address' => 'Industriestr. 16',
						'sc_zip' => '67269',
						'sc_city' => 'Grünstadt/Pfalz',
						'sc_phone' => '0 63 59 - 8 30 22',
						'last_visit' => '2019-07-24T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '2',
						'mailing_product' => '12'
					],
					'id' => 'nlbs2015@yahoo.de',
				],
				[
					'data' => [
						'salutation' => 'HERR',
						'title' => '',
						'firstname' => '',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-014',
						'sc_id' => '250',
						'sc_name' => 'Euromaster Berlin-Hohenschoenhausen',
						'sc_address' => 'Gehrenseestr. 43',
						'sc_zip' => '13053',
						'sc_city' => 'Berlin-Hohenschoenhausen',
						'sc_phone' => '0 30 - 93 52 36 00',
						'last_visit' => '2019-07-24T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '1',
						'mailing_product' => '14'
					],
					'id' => 'nlbs2015@aol.de',
				],
				[
					'data' => [
						'salutation' => 'FIRMA',
						'title' => '',
						'firstname' => '',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'AB-015',
						'sc_id' => '252',
						'sc_name' => 'Euromaster Berlin-Bohnstorf bei Schoenefeld',
						'sc_address' => 'Grünbergallee 274',
						'sc_zip' => '12526',
						'sc_city' => 'Berlin-Bohnstorf bei Schoenefeld',
						'sc_phone' => '0 30 - 67 68 90 33',
						'last_visit' => '2019-07-24T00:00:00',
						'hu_date' => 'Juli 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '2',
						'mailing_product' => '15'
					],
					'id' => 'nlbs2015@gmail.com',
				],
				[
					'data' => [
						'salutation' => 'FRAU',
						'title' => '',
						'firstname' => '',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'HU-300',
						'sc_id' => '327',
						'sc_name' => 'Euromaster Mönchengladbach-Rheydt',
						'sc_address' => 'Giesenkirchener Str. 17',
						'sc_zip' => '41238',
						'sc_city' => 'Mönchengladbach-Rheydt',
						'sc_phone' => '0 21 66 - 18 70 51',
						'last_visit' => '2019-07-24T00:00:00',
						'hu_date' => 'August 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '3',
						'mailing_product' => '0'
					],
					'id' => 'nlbs2015@outlook.de',
				],
				[
					'data' => [
						'salutation' => 'HERR',
						'title' => '',
						'firstname' => '',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'HU-400',
						'sc_id' => '558',
						'sc_name' => 'Euromaster Bad Camberg',
						'sc_address' => 'Limburger Str. 51-53',
						'sc_zip' => '65520',
						'sc_city' => 'Bad Camberg',
						'sc_phone' => '0 64 34 - 50 11',
						'last_visit' => '2019-01-14T00:00:00',
						'hu_date' => 'Januar 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '4',
						'mailing_product' => '0'
					],
					'id' => 'nlbs2015@freenet.de',
				],
				[
					'data' => [
						'salutation' => 'FIRMA',
						'title' => '',
						'firstname' => '',
						'lastname' => 'Mustermann',
						'car_license_plate' => 'HU-401',
						'sc_id' => '504',
						'sc_name' => 'Euromaster Grünstadt/Pfalz',
						'sc_address' => 'Industriestr. 16',
						'sc_zip' => '67269',
						'sc_city' => 'Grünstadt/Pfalz',
						'sc_phone' => '0 63 59 - 8 30 22',
						'last_visit' => '2019-01-14T00:00:00',
						'hu_date' => 'Januar 2019',
						'mailing_trigger' => $mailingTrigger,
						'mailing_reason' => '4',
						'mailing_product' => '1'
					],
					'id' => 'e_m_m@gmx.de',
				],
			]
		];
	}
}
